let tabs = [];

// Initialize
window.onload = async () => {
    try {
        await refreshTabs();
        window.runtime.EventsOn("tab-updated", (updatedTab) => {
            console.log("Tab updated:", updatedTab);
            refreshTabs();
        });
    } catch (err) {
        console.error(err);
    }
};

async function refreshTabs() {
    tabs = await window.go.main.App.GetTabs();
    renderTabs();
}

async function renderTabs() {
    const grid = document.getElementById('tab-grid');
    grid.innerHTML = '';

    for (const tab of tabs) {
        const card = document.createElement('div');
        card.className = 'tab-card';
        card.onclick = () => openTab(tab.id);

        let coverHtml = `<div class="placeholder-cover">🎵</div>`;
        if (tab.coverPath) {
            try {
                const b64 = await window.go.main.App.GetCover(tab.coverPath);
                if (b64) {
                    coverHtml = `<img src="data:image/jpeg;base64,${b64}" class="cover-img" loading="lazy">`;
                }
            } catch (e) { console.error("Error loading cover", e); }
        }

        card.innerHTML = `
            <div class="cover-wrapper">
                ${coverHtml}
            </div>
            <div class="info">
                <div class="title" title="${tab.title}">${tab.title}</div>
                <div class="artist" title="${tab.artist}">${tab.artist}</div>
                <div class="type-badge">${tab.type}</div>
            </div>
        `;
        grid.appendChild(card);
    }
}

async function addTab(isUpload) {
    try {
        const path = await window.runtime.WindowOpenFileDialog({
            Title: "Select Tab File",
            Filters: [
                { DisplayName: "Tabs (*.pdf;*.gp;*.gp5;*.gpx)", Pattern: "*.pdf;*.gp;*.gp5;*.gpx" }
            ]
        });

        if (path) {
            const tabData = await window.go.main.App.ProcessFile(path);
            openModal(tabData, isUpload);
        }
    } catch (err) {
        console.error(err);
    }
}

function openModal(tabData, isUpload) {
    document.getElementById('edit-path').value = tabData.filePath;
    document.getElementById('edit-copy').value = isUpload ? "true" : "false";
    document.getElementById('edit-title').value = tabData.title;
    document.getElementById('edit-artist').value = tabData.artist;
    document.getElementById('edit-album').value = tabData.album;
    document.getElementById('edit-type').value = tabData.type;

    // Store temporary ID or just create new one on save? 
    // The tabData has an ID generated by backend. We'll use it.
    // We attach it to the form element data-id or just reconstruct.
    // Actually, ProcessFile returns a struct with ID. We should pass that ID back if we want to use it,
    // but SaveTab expects a full struct. We'll reconstruct the struct from inputs.
    // To keep it simple, we'll store the ID in a hidden field or dataset.
    document.getElementById('edit-form').dataset.id = tabData.id;

    document.getElementById('modal-overlay').classList.remove('hidden');
}

function closeModal() {
    document.getElementById('modal-overlay').classList.add('hidden');
    document.getElementById('edit-form').reset();
}

async function saveTab() {
    const id = document.getElementById('edit-form').dataset.id;
    const path = document.getElementById('edit-path').value;
    const shouldCopy = document.getElementById('edit-copy').value === "true";
    const title = document.getElementById('edit-title').value;
    const artist = document.getElementById('edit-artist').value;
    const album = document.getElementById('edit-album').value;
    const type = document.getElementById('edit-type').value;

    const tab = {
        id: id,
        title: title,
        artist: artist,
        album: album,
        filePath: path,
        type: type,
        // isManaged handled by backend based on copy flag
        coverPath: "" // backend will fill
    };

    try {
        await window.go.main.App.SaveTab(tab, shouldCopy);
        closeModal();
        refreshTabs();
    } catch (err) {
        alert("Error saving tab: " + err);
    }
}

async function openTab(id) {
    try {
        await window.go.main.App.OpenTab(id);
    } catch (err) {
        console.error(err);
        alert("Failed to open tab");
    }
}
