// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Capabilities {
    "target": Target;
    "formFactor": FormFactor;
    "nativeTopLevelTabs": boolean;
    "webTopLevelTabs": boolean;
    "inProcessContent": boolean;
    "loopbackContent": boolean;
    "nativeFileImport": boolean;
    "safeAreaInsets": boolean;
    "folderWatcher": boolean;
    "customStoragePaths": boolean;
    "plugins": boolean;
    "webMIDI": boolean;
    "selfUpdate": boolean;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("target" in $$source)) {
            this["target"] = Target.$zero;
        }
        if (!("formFactor" in $$source)) {
            this["formFactor"] = FormFactor.$zero;
        }
        if (!("nativeTopLevelTabs" in $$source)) {
            this["nativeTopLevelTabs"] = false;
        }
        if (!("webTopLevelTabs" in $$source)) {
            this["webTopLevelTabs"] = false;
        }
        if (!("inProcessContent" in $$source)) {
            this["inProcessContent"] = false;
        }
        if (!("loopbackContent" in $$source)) {
            this["loopbackContent"] = false;
        }
        if (!("nativeFileImport" in $$source)) {
            this["nativeFileImport"] = false;
        }
        if (!("safeAreaInsets" in $$source)) {
            this["safeAreaInsets"] = false;
        }
        if (!("folderWatcher" in $$source)) {
            this["folderWatcher"] = false;
        }
        if (!("customStoragePaths" in $$source)) {
            this["customStoragePaths"] = false;
        }
        if (!("plugins" in $$source)) {
            this["plugins"] = false;
        }
        if (!("webMIDI" in $$source)) {
            this["webMIDI"] = false;
        }
        if (!("selfUpdate" in $$source)) {
            this["selfUpdate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

export enum FormFactor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormFactorPhone = "phone",
    FormFactorTablet = "tablet",
    FormFactorDesktop = "desktop",
};

export enum Target {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetDesktop = "desktop",
    TargetIOS = "ios",
    TargetAndroid = "android",
};
