// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function AddCategory(arg1:store.Category):Promise<void>;

export function AddTabToCategory(arg1:string,arg2:string):Promise<void>;

export function BatchAddTabsToCategory(arg1:Array<string>,arg2:string):Promise<number>;

export function BatchDeleteTabs(arg1:Array<string>):Promise<number>;

export function BatchMoveTabs(arg1:Array<string>,arg2:string):Promise<number>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteTab(arg1:string):Promise<void>;

export function DownloadCloudTabToLocal(arg1:string):Promise<void>;

export function ExportTab(arg1:string,arg2:string):Promise<void>;

export function GetCategories():Promise<Array<store.Category>>;

export function GetCover(arg1:string):Promise<string>;

export function GetFileServerPort():Promise<number>;

export function GetRecentCategories(arg1:number):Promise<Array<store.Category>>;

export function GetRecentTabs(arg1:number):Promise<Array<store.Tab>>;

export function GetSettings():Promise<store.Settings>;

export function GetTabs():Promise<Array<store.Tab>>;

export function GetTabsPaginated(arg1:string,arg2:number,arg3:number,arg4:string,arg5:Array<string>,arg6:boolean,arg7:string,arg8:boolean):Promise<main.TabsResponse>;

export function MarkAsOpened(arg1:string):Promise<void>;

export function MoveCategory(arg1:string,arg2:string):Promise<void>;

export function MoveTab(arg1:string,arg2:string):Promise<void>;

export function OpenTab(arg1:string):Promise<void>;

export function ProcessFile(arg1:string):Promise<store.Tab>;

export function RemoveTabFromCategory(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function SaveTab(arg1:store.Tab,arg2:boolean):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SelectImage():Promise<string>;

export function SetFileServerPort(arg1:number):Promise<void>;

export function TriggerSync():Promise<string>;

export function UpdateTab(arg1:store.Tab):Promise<void>;

export function UpdateTabCategories(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateTabMetadata(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WebDAVAddOnlineFiles(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function WebDAVCheckStatus():Promise<boolean>;

export function WebDAVDownloadFiles(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function WebDAVListDir(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<store.RemoteFile>>;

export function WebDAVListRemoteDirectories(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function WebDAVScanRemoteFiles(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<store.RemoteFile>>;

export function WebDAVTestConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WebDAVUploadFiles(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<void>;
