// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function BatchDeleteTabs(arg1) {
  return window['go']['main']['App']['BatchDeleteTabs'](arg1);
}

export function BatchMoveTabs(arg1, arg2) {
  return window['go']['main']['App']['BatchMoveTabs'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteTab(arg1) {
  return window['go']['main']['App']['DeleteTab'](arg1);
}

export function ExportTab(arg1, arg2) {
  return window['go']['main']['App']['ExportTab'](arg1, arg2);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCover(arg1) {
  return window['go']['main']['App']['GetCover'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTabContent(arg1) {
  return window['go']['main']['App']['GetTabContent'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function GetTabsPaginated(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetTabsPaginated'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function MoveCategory(arg1, arg2) {
  return window['go']['main']['App']['MoveCategory'](arg1, arg2);
}

export function MoveTab(arg1, arg2) {
  return window['go']['main']['App']['MoveTab'](arg1, arg2);
}

export function OpenTab(arg1) {
  return window['go']['main']['App']['OpenTab'](arg1);
}

export function ProcessFile(arg1) {
  return window['go']['main']['App']['ProcessFile'](arg1);
}

export function ReadPDF(arg1) {
  return window['go']['main']['App']['ReadPDF'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTab(arg1, arg2) {
  return window['go']['main']['App']['SaveTab'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function TriggerSync() {
  return window['go']['main']['App']['TriggerSync']();
}

export function UpdateTab(arg1) {
  return window['go']['main']['App']['UpdateTab'](arg1);
}
