// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Category represents a grouping of tabs
 */
export class Category {
    "id": string;
    "name": string;

    /**
     * Empty if root
     */
    "parentId": string;

    /**
     * Custom cover path (raw)
     */
    "coverPath": string;

    /**
     * Derived or custom
     */
    "effectiveCoverPath": string;

    /** Creates a new Category instance. */
    constructor($$source: Partial<Category> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }
        if (!("coverPath" in $$source)) {
            this["coverPath"] = "";
        }
        if (!("effectiveCoverPath" in $$source)) {
            this["effectiveCoverPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     */
    static createFrom($$source: any = {}): Category {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category($$parsedSource as Partial<Category>);
    }
}

/**
 * CloudVolume represents a virtual volume (physical cloud drive) mounted via WebDAV
 */
export class CloudVolume {
    /**
     * UUID generated on first scan
     */
    "id": string;

    /**
     * User-friendly name (e.g., "Google Drive", "OneDrive")
     */
    "name": string;

    /**
     * Current mount path in WebDAV (e.g., "/gdrive")
     */
    "mountPath": string;

    /**
     * Path to fingerprint file (e.g., "/gdrive/.haya-volume-fingerprint")
     */
    "fingerprintPath": string;

    /**
     * Unix timestamp when volume was first registered
     */
    "createdAt": number;

    /**
     * Unix timestamp when volume was last detected
     */
    "lastSeenAt": number;

    /**
     * True if volume is currently accessible
     */
    "isAvailable": boolean;

    /** Creates a new CloudVolume instance. */
    constructor($$source: Partial<CloudVolume> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mountPath" in $$source)) {
            this["mountPath"] = "";
        }
        if (!("fingerprintPath" in $$source)) {
            this["fingerprintPath"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("lastSeenAt" in $$source)) {
            this["lastSeenAt"] = 0;
        }
        if (!("isAvailable" in $$source)) {
            this["isAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudVolume instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudVolume {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudVolume($$parsedSource as Partial<CloudVolume>);
    }
}

/**
 * KeyBindings represents user-configurable keyboard shortcuts
 */
export class KeyBindings {
    "scrollDown": string;
    "scrollUp": string;
    "metronome": string;
    "playPause": string;
    "stop": string;
    "bpmPlus": string;
    "bpmMinus": string;
    "toggleLoop": string;
    "clearSelection": string;
    "jumpToBar": string;
    "jumpToStart": string;
    "autoScroll": string;
    "scrollSpeedUp": string;
    "scrollSpeedDown": string;

    /** Creates a new KeyBindings instance. */
    constructor($$source: Partial<KeyBindings> = {}) {
        if (!("scrollDown" in $$source)) {
            this["scrollDown"] = "";
        }
        if (!("scrollUp" in $$source)) {
            this["scrollUp"] = "";
        }
        if (!("metronome" in $$source)) {
            this["metronome"] = "";
        }
        if (!("playPause" in $$source)) {
            this["playPause"] = "";
        }
        if (!("stop" in $$source)) {
            this["stop"] = "";
        }
        if (!("bpmPlus" in $$source)) {
            this["bpmPlus"] = "";
        }
        if (!("bpmMinus" in $$source)) {
            this["bpmMinus"] = "";
        }
        if (!("toggleLoop" in $$source)) {
            this["toggleLoop"] = "";
        }
        if (!("clearSelection" in $$source)) {
            this["clearSelection"] = "";
        }
        if (!("jumpToBar" in $$source)) {
            this["jumpToBar"] = "";
        }
        if (!("jumpToStart" in $$source)) {
            this["jumpToStart"] = "";
        }
        if (!("autoScroll" in $$source)) {
            this["autoScroll"] = "";
        }
        if (!("scrollSpeedUp" in $$source)) {
            this["scrollSpeedUp"] = "";
        }
        if (!("scrollSpeedDown" in $$source)) {
            this["scrollSpeedDown"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyBindings instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyBindings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyBindings($$parsedSource as Partial<KeyBindings>);
    }
}

/**
 * MidiMapping represents a MIDI message mapping
 */
export class MidiMapping {
    /**
     * "CC", "Note"
     */
    "type": string;

    /**
     * CC number or Note number
     */
    "number": number;

    /**
     * 0-15
     */
    "channel": number;

    /** Creates a new MidiMapping instance. */
    constructor($$source: Partial<MidiMapping> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("channel" in $$source)) {
            this["channel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MidiMapping instance from a string or object.
     */
    static createFrom($$source: any = {}): MidiMapping {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MidiMapping($$parsedSource as Partial<MidiMapping>);
    }
}

/**
 * MidiSettings represents MIDI-related configuration
 */
export class MidiSettings {
    "enabled": boolean;
    "scrollDown": MidiMapping | null;
    "scrollUp": MidiMapping | null;
    "playPause": MidiMapping | null;
    "expressionScroll": MidiMapping | null;

    /** Creates a new MidiSettings instance. */
    constructor($$source: Partial<MidiSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("scrollDown" in $$source)) {
            this["scrollDown"] = null;
        }
        if (!("scrollUp" in $$source)) {
            this["scrollUp"] = null;
        }
        if (!("playPause" in $$source)) {
            this["playPause"] = null;
        }
        if (!("expressionScroll" in $$source)) {
            this["expressionScroll"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MidiSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): MidiSettings {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scrollDown" in $$parsedSource) {
            $$parsedSource["scrollDown"] = $$createField1_0($$parsedSource["scrollDown"]);
        }
        if ("scrollUp" in $$parsedSource) {
            $$parsedSource["scrollUp"] = $$createField2_0($$parsedSource["scrollUp"]);
        }
        if ("playPause" in $$parsedSource) {
            $$parsedSource["playPause"] = $$createField3_0($$parsedSource["playPause"]);
        }
        if ("expressionScroll" in $$parsedSource) {
            $$parsedSource["expressionScroll"] = $$createField4_0($$parsedSource["expressionScroll"]);
        }
        return new MidiSettings($$parsedSource as Partial<MidiSettings>);
    }
}

export class RemoteFile {
    "name": string;

    /**
     * Full remote path
     */
    "path": string;
    "size": number;
    "isDir": boolean;

    /** Creates a new RemoteFile instance. */
    constructor($$source: Partial<RemoteFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteFile instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteFile($$parsedSource as Partial<RemoteFile>);
    }
}

/**
 * Settings represents application configuration
 */
export class Settings {
    /**
     * "dark", "light", "system"
     */
    "theme": string;

    /**
     * "en", "zh-CN", "zh-TW", "ja"
     */
    "language": string;

    /**
     * URL or path
     */
    "background": string;

    /**
     * "url", "local"
     */
    "bgType": string;

    /**
     * "system", "inner"
     */
    "openMethod": string;

    /**
     * "system", "inner"
     */
    "openGpMethod": string;

    /**
     * Device ID for audio output
     */
    "audioDevice": string;
    "syncPaths": string[];

    /**
     * "skip", "overwrite"
     */
    "syncStrategy": string;
    "autoSyncEnabled": boolean;

    /**
     * "startup", "weekly", "monthly", "yearly"
     */
    "autoSyncFrequency": string;

    /**
     * Unix timestamp
     */
    "lastSyncTime": number;
    "keyBindings": KeyBindings;
    "midiSettings": MidiSettings;

    /**
     * Custom storage path
     */
    "storagePath": string;

    /**
     * Custom covers path
     */
    "coversPath": string;

    /**
     * Update Check
     */
    "updateCheckEnabled": boolean;
    "lastUpdateCheckTime": number;
    "latestVersion": string;

    /**
     * WebDAV Settings
     */
    "webdavEnabled": boolean;
    "webdavUrl": string;
    "webdavUser": string;
    "webdavPassword": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }
        if (!("bgType" in $$source)) {
            this["bgType"] = "";
        }
        if (!("openMethod" in $$source)) {
            this["openMethod"] = "";
        }
        if (!("openGpMethod" in $$source)) {
            this["openGpMethod"] = "";
        }
        if (!("audioDevice" in $$source)) {
            this["audioDevice"] = "";
        }
        if (!("syncPaths" in $$source)) {
            this["syncPaths"] = [];
        }
        if (!("syncStrategy" in $$source)) {
            this["syncStrategy"] = "";
        }
        if (!("autoSyncEnabled" in $$source)) {
            this["autoSyncEnabled"] = false;
        }
        if (!("autoSyncFrequency" in $$source)) {
            this["autoSyncFrequency"] = "";
        }
        if (!("lastSyncTime" in $$source)) {
            this["lastSyncTime"] = 0;
        }
        if (!("keyBindings" in $$source)) {
            this["keyBindings"] = (new KeyBindings());
        }
        if (!("midiSettings" in $$source)) {
            this["midiSettings"] = (new MidiSettings());
        }
        if (!("storagePath" in $$source)) {
            this["storagePath"] = "";
        }
        if (!("coversPath" in $$source)) {
            this["coversPath"] = "";
        }
        if (!("updateCheckEnabled" in $$source)) {
            this["updateCheckEnabled"] = false;
        }
        if (!("lastUpdateCheckTime" in $$source)) {
            this["lastUpdateCheckTime"] = 0;
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("webdavEnabled" in $$source)) {
            this["webdavEnabled"] = false;
        }
        if (!("webdavUrl" in $$source)) {
            this["webdavUrl"] = "";
        }
        if (!("webdavUser" in $$source)) {
            this["webdavUser"] = "";
        }
        if (!("webdavPassword" in $$source)) {
            this["webdavPassword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField7_0 = $$createType2;
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("syncPaths" in $$parsedSource) {
            $$parsedSource["syncPaths"] = $$createField7_0($$parsedSource["syncPaths"]);
        }
        if ("keyBindings" in $$parsedSource) {
            $$parsedSource["keyBindings"] = $$createField12_0($$parsedSource["keyBindings"]);
        }
        if ("midiSettings" in $$parsedSource) {
            $$parsedSource["midiSettings"] = $$createField13_0($$parsedSource["midiSettings"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Tab represents a guitar tab file and its metadata
 */
export class Tab {
    "id": string;
    "title": string;
    "artist": string;
    "album": string;

    /**
     * For local: absolute path. For cloud: relative path within volume
     */
    "filePath": string;

    /**
     * Relative path within volume (persists after download)
     */
    "cloudPath": string;

    /**
     * Cloud volume ID (empty for local files)
     */
    "volumeId": string;

    /**
     * "pdf" or "gp"
     */
    "type": string;
    "isManaged": boolean;

    /**
     * True if this is a cloud/online tab (not downloaded)
     */
    "isCloud": boolean;
    "coverPath": string;

    /**
     * List of Category IDs
     */
    "categoryIds": string[];

    /**
     * e.g. "US", "JP" (user's preferred search country)
     */
    "country": string;

    /**
     * e.g. "ja_jp"
     */
    "language": string;

    /**
     * Artist's origin country from MusicBrainz (e.g. "JP", "CN", "US")
     */
    "originCountry": string;

    /**
     * e.g. "Lead Guitar", "First Version"
     */
    "tag": string;

    /**
     * Unix timestamp
     */
    "addedAt": number;

    /**
     * Unix timestamp
     */
    "lastOpened": number;

    /**
     * A-Z initial for EN/ZH UI (Pinyin/Romaji mapped to A-Z)
     */
    "initialAz": string;

    /**
     * Kana initial for JA UI (あかさたな... or A-Z for Latin)
     */
    "initialKana": string;

    /** Creates a new Tab instance. */
    constructor($$source: Partial<Tab> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("cloudPath" in $$source)) {
            this["cloudPath"] = "";
        }
        if (!("volumeId" in $$source)) {
            this["volumeId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("isManaged" in $$source)) {
            this["isManaged"] = false;
        }
        if (!("isCloud" in $$source)) {
            this["isCloud"] = false;
        }
        if (!("coverPath" in $$source)) {
            this["coverPath"] = "";
        }
        if (!("categoryIds" in $$source)) {
            this["categoryIds"] = [];
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("originCountry" in $$source)) {
            this["originCountry"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("addedAt" in $$source)) {
            this["addedAt"] = 0;
        }
        if (!("lastOpened" in $$source)) {
            this["lastOpened"] = 0;
        }
        if (!("initialAz" in $$source)) {
            this["initialAz"] = "";
        }
        if (!("initialKana" in $$source)) {
            this["initialKana"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tab instance from a string or object.
     */
    static createFrom($$source: any = {}): Tab {
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categoryIds" in $$parsedSource) {
            $$parsedSource["categoryIds"] = $$createField11_0($$parsedSource["categoryIds"]);
        }
        return new Tab($$parsedSource as Partial<Tab>);
    }
}

// Private type creation functions
const $$createType0 = MidiMapping.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = KeyBindings.createFrom;
const $$createType4 = MidiSettings.createFrom;
