// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct holds all application dependencies and state
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../pkg/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCategory adds a new category
 */
export function AddCategory(cat: store$0.Category): $CancellablePromise<void> {
    return $Call.ByID(3334367430, cat);
}

/**
 * AddTabToCategory adds a tab to a category without removing it from others
 */
export function AddTabToCategory(tabID: string, categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(475388820, tabID, categoryID);
}

/**
 * BatchAddTabsToCategory adds multiple tabs to a category
 */
export function BatchAddTabsToCategory(ids: string[], categoryID: string): $CancellablePromise<number> {
    return $Call.ByID(943914429, ids, categoryID);
}

/**
 * BatchDeleteTabs deletes multiple tabs at once
 */
export function BatchDeleteTabs(ids: string[]): $CancellablePromise<number> {
    return $Call.ByID(210833462, ids);
}

/**
 * BatchMoveTabs moves multiple tabs to a category at once (replaces existing categories)
 */
export function BatchMoveTabs(ids: string[], categoryID: string): $CancellablePromise<number> {
    return $Call.ByID(2730224280, ids, categoryID);
}

/**
 * CheckMigration checks if a directory needs migration and returns the number of files and total size
 */
export function CheckMigration(target: string): $CancellablePromise<$models.MigrationStatus> {
    return $Call.ByID(3787843539, target).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteCategory deletes a category
 */
export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(634846304, id);
}

/**
 * DeleteTab deletes a tab and its managed file if applicable
 */
export function DeleteTab(id: string): $CancellablePromise<void> {
    return $Call.ByID(4017381303, id);
}

/**
 * DomReady is called after the front-end dom has been loaded
 */
export function DomReady(): $CancellablePromise<void> {
    return $Call.ByID(1747675608);
}

/**
 * DownloadCloudTabToLocal downloads a cloud tab to local storage
 * IMPORTANT: This preserves existing metadata - does NOT re-parse the file
 */
export function DownloadCloudTabToLocal(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(2288500429, tabID);
}

/**
 * ExportTab copies the tab file to a destination folder
 */
export function ExportTab(id: string, destFolder: string): $CancellablePromise<void> {
    return $Call.ByID(2376548936, id, destFolder);
}

/**
 * GetAppVersion returns the current application version
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(582610352);
}

/**
 * GetCategories returns the list of categories
 */
export function GetCategories(): $CancellablePromise<store$0.Category[]> {
    return $Call.ByID(1973231133).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetCover returns the base64 encoded image
 */
export function GetCover(path: string): $CancellablePromise<string> {
    return $Call.ByID(3366959344, path);
}

export function GetCoverContentURL(id: string): $CancellablePromise<string> {
    return $Call.ByID(1707724014, id);
}

/**
 * GetCoversDir returns the directory for cover images.
 */
export function GetCoversDir(): $CancellablePromise<string> {
    return $Call.ByID(3852511304);
}

/**
 * GetFileServerPort returns the port of the local file server
 */
export function GetFileServerPort(): $CancellablePromise<number> {
    return $Call.ByID(476865099);
}

/**
 * GetPlugins returns information for all loaded plugins.
 */
export function GetPlugins(): $CancellablePromise<$models.PluginInfo[]> {
    return $Call.ByID(1125007675).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRecentCategories returns the list of recently accessed categories
 */
export function GetRecentCategories(limit: number): $CancellablePromise<store$0.Category[]> {
    return $Call.ByID(37050222, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRecentTabs returns the list of recently accessed tabs
 */
export function GetRecentTabs(limit: number): $CancellablePromise<store$0.Tab[]> {
    return $Call.ByID(2900273882, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetRuntimeCapabilities(viewportWidth: number): $CancellablePromise<platform$0.Capabilities> {
    return $Call.ByID(776383673, viewportWidth).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSettings returns the current settings
 */
export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(1498150232).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetStorageDir returns the directory for managed tabs.
 */
export function GetStorageDir(): $CancellablePromise<string> {
    return $Call.ByID(3184726253);
}

/**
 * GetTabAnnotations returns page-level annotation JSON data for a tab.
 * Returns "[]" when no annotation exists for this page.
 */
export function GetTabAnnotations(tabID: string, pageNumber: number): $CancellablePromise<string> {
    return $Call.ByID(4116741406, tabID, pageNumber);
}

export function GetTabContentURL(id: string): $CancellablePromise<string> {
    return $Call.ByID(2639814362, id);
}

/**
 * GetTabs returns the list of tabs (backward compatibility)
 */
export function GetTabs(): $CancellablePromise<store$0.Tab[]> {
    return $Call.ByID(1852821949).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetTabsPaginated returns a paginated list of tabs with optional search
 */
export function GetTabsPaginated(categoryId: string, page: number, pageSize: number, searchQuery: string, filterBy: string[], isGlobal: boolean, sortBy: string, sortDesc: boolean): $CancellablePromise<$models.TabsResponse> {
    return $Call.ByID(3108702856, categoryId, page, pageSize, searchQuery, filterBy, isGlobal, sortBy, sortDesc).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * HasPlugins checks whether any plugins are loaded.
 */
export function HasPlugins(): $CancellablePromise<boolean> {
    return $Call.ByID(1977258271);
}

/**
 * MarkAsOpened updates the LastOpened timestamp for a tab without opening it
 */
export function MarkAsOpened(id: string): $CancellablePromise<void> {
    return $Call.ByID(2768322691, id);
}

/**
 * MigrateData migrates data from the current directory to the new path
 */
export function MigrateData(target: string, newPath: string, copyOnly: boolean): $CancellablePromise<void> {
    return $Call.ByID(1888995128, target, newPath, copyOnly);
}

/**
 * MoveCategory moves a category into another category
 */
export function MoveCategory(id: string, newParentID: string): $CancellablePromise<void> {
    return $Call.ByID(1465876250, id, newParentID);
}

/**
 * MoveTab updates the category of a tab (replaces existing categories with this one)
 */
export function MoveTab(tabID: string, categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(2418525889, tabID, categoryID);
}

/**
 * OpenTab opens the file using system default
 */
export function OpenTab(id: string): $CancellablePromise<void> {
    return $Call.ByID(452447502, id);
}

/**
 * ProcessFile delegates to SyncService for file processing
 */
export function ProcessFile(path: string): $CancellablePromise<store$0.Tab> {
    return $Call.ByID(3265479686, path).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RecalculateAllInitials forces recalculation of initials for all tabs
 */
export function RecalculateAllInitials(): $CancellablePromise<number> {
    return $Call.ByID(307206764);
}

/**
 * RemoveTabFromCategory removes a tab from a category
 */
export function RemoveTabFromCategory(tabID: string, categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(2760581602, tabID, categoryID);
}

/**
 * ResolveCoverPath converts a relative path to absolute using GetCoversDir.
 */
export function ResolveCoverPath(path: string): $CancellablePromise<string> {
    return $Call.ByID(3664384055, path);
}

/**
 * ResolveTabPath converts a relative path to absolute using GetStorageDir.
 */
export function ResolveTabPath(path: string, isManaged: boolean): $CancellablePromise<string> {
    return $Call.ByID(3794757723, path, isManaged);
}

/**
 * SaveSettings updates the settings
 */
export function SaveSettings(s: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2233870179, s);
}

/**
 * SaveTab saves the tab. copyFile determines if we import it to internal storage.
 * The passed tab should have the user-confirmed Metadata.
 * Returns the saved tab on success.
 */
export function SaveTab(tab: store$0.Tab, shouldCopy: boolean): $CancellablePromise<store$0.Tab | null> {
    return $Call.ByID(3164259813, tab, shouldCopy).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SaveTabAnnotations saves page-level annotation JSON data for a tab.
 */
export function SaveTabAnnotations(tabID: string, pageNumber: number, jsonData: string): $CancellablePromise<void> {
    return $Call.ByID(2775041665, tabID, pageNumber, jsonData);
}

/**
 * SelectFiles opens a file dialog and returns the selected file paths
 */
export function SelectFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(1977005426).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SelectFolder opens a folder selection dialog
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(3708125183);
}

/**
 * SelectImage opens a file dialog for selecting images
 */
export function SelectImage(): $CancellablePromise<string> {
    return $Call.ByID(3641615136);
}

/**
 * SetApp sets the Wails application instance
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3120920536, app);
}

/**
 * SetFileServerPort sets the port of the local file server
 */
export function SetFileServerPort(port: number): $CancellablePromise<void> {
    return $Call.ByID(1854940783, port);
}

/**
 * Shutdown is called when the app is closing
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(1704108193);
}

/**
 * StartFileServer starts a local HTTP server to serve files
 */
export function StartFileServer(): $CancellablePromise<number> {
    return $Call.ByID(4025964084);
}

/**
 * Startup is called when the app starts.
 */
export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(1481138364);
}

/**
 * TriggerSync delegates to SyncService for file synchronization.
 * It also notifies the PluginManager that a new sync run is starting so
 * plugins can reset per-run counters (e.g. AI request limits).
 */
export function TriggerSync(): $CancellablePromise<string> {
    return $Call.ByID(103524186);
}

/**
 * UpdatePluginConfig updates a plugin's configuration and enabled state.
 */
export function UpdatePluginConfig(id: string, config: { [_ in string]?: string }, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2204878215, id, config, enabled);
}

/**
 * UpdateTab updates an existing tab's metadata
 */
export function UpdateTab(tab: store$0.Tab): $CancellablePromise<void> {
    return $Call.ByID(3982642153, tab);
}

/**
 * UpdateTabCategories updates the categories for a tab
 */
export function UpdateTabCategories(tabID: string, categoryIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(736261881, tabID, categoryIDs);
}

/**
 * UpdateTabMetadata updates only the metadata fields (title, artist, album) for a tab.
 * This is called by the frontend after AlphaTab parses the file's internal metadata.
 * It implements a "smart update" strategy:
 * - If no cover exists: prefer AlphaTab's data (more authoritative than filename parsing)
 * - If cover exists: only update placeholder fields (existing data was good enough for cover search)
 */
export function UpdateTabMetadata(id: string, title: string, artist: string, album: string): $CancellablePromise<void> {
    return $Call.ByID(863124108, id, title, artist, album);
}

/**
 * WebDAVAddOnlineFiles adds cloud files to library without downloading (lazy loading)
 */
export function WebDAVAddOnlineFiles(url: string, user: string, password: string, remotePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1226787765, url, user, password, remotePaths);
}

/**
 * WebDAVCheckStatus checks if WebDAV connection is available
 */
export function WebDAVCheckStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(2289385120);
}

/**
 * WebDAVCheckVolumeHealth checks the health of all registered volumes
 */
export function WebDAVCheckVolumeHealth(): $CancellablePromise<{ [_ in string]?: boolean }> {
    return $Call.ByID(2656731494).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * WebDAVCleanupOrphanedTabs removes tabs that reference non-existent volumes
 */
export function WebDAVCleanupOrphanedTabs(): $CancellablePromise<number> {
    return $Call.ByID(3596610121);
}

/**
 * WebDAVCreateVolume creates a new volume with a fingerprint file
 */
export function WebDAVCreateVolume(volumeName: string, remotePath: string): $CancellablePromise<store$0.CloudVolume | null> {
    return $Call.ByID(2126856860, volumeName, remotePath).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * WebDAVDiscoverVolumes scans WebDAV for all volumes and registers them
 * This is the entry point for multi-device sync
 */
export function WebDAVDiscoverVolumes(): $CancellablePromise<store$0.CloudVolume[]> {
    return $Call.ByID(3232619432).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * WebDAVDownloadFiles downloads selected files and processes them
 */
export function WebDAVDownloadFiles(url: string, user: string, password: string, remotePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1238554137, url, user, password, remotePaths);
}

/**
 * WebDAVGetOrphanedTabsCount returns the count of tabs referencing non-existent volumes
 */
export function WebDAVGetOrphanedTabsCount(): $CancellablePromise<number> {
    return $Call.ByID(354419180);
}

/**
 * WebDAVInitialize initializes the WebDAV volume system
 * This should be called on app startup if WebDAV is enabled
 */
export function WebDAVInitialize(): $CancellablePromise<void> {
    return $Call.ByID(3618666404);
}

/**
 * WebDAVIsReady checks if WebDAV is fully ready for use (connected + volumes initialized)
 */
export function WebDAVIsReady(): $CancellablePromise<boolean> {
    return $Call.ByID(1388200009);
}

/**
 * WebDAVListDir lists files and directories in a remote path (non-recursive)
 */
export function WebDAVListDir(url: string, user: string, password: string, dir: string): $CancellablePromise<store$0.RemoteFile[]> {
    return $Call.ByID(1130914849, url, user, password, dir).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * WebDAVListRemoteDirectories lists directories in a remote path
 */
export function WebDAVListRemoteDirectories(url: string, user: string, password: string, dir: string): $CancellablePromise<string[]> {
    return $Call.ByID(3488981299, url, user, password, dir).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * WebDAVMigrateCloudTabs migrates existing cloud tabs to use the volume system
 */
export function WebDAVMigrateCloudTabs(): $CancellablePromise<void> {
    return $Call.ByID(3210201376);
}

/**
 * WebDAVReconnect attempts to reconnect and reinitialize WebDAV
 * This should be called when connection is restored after being lost
 */
export function WebDAVReconnect(): $CancellablePromise<void> {
    return $Call.ByID(2779643383);
}

/**
 * WebDAVScanRemoteFiles scans a remote directory
 */
export function WebDAVScanRemoteFiles(url: string, user: string, password: string, dir: string): $CancellablePromise<store$0.RemoteFile[]> {
    return $Call.ByID(2926196124, url, user, password, dir).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * WebDAVTestConnection tests the WebDAV connection
 */
export function WebDAVTestConnection(url: string, user: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3740757906, url, user, password);
}

/**
 * WebDAVUploadFiles uploads local files to a remote directory
 */
export function WebDAVUploadFiles(url: string, user: string, password: string, localPaths: string[], remoteDir: string): $CancellablePromise<void> {
    return $Call.ByID(1957189098, url, user, password, localPaths, remoteDir);
}

// Private type creation functions
const $$createType0 = $models.MigrationStatus.createFrom;
const $$createType1 = store$0.Category.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.PluginInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = store$0.Tab.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = platform$0.Capabilities.createFrom;
const $$createType8 = store$0.Settings.createFrom;
const $$createType9 = $models.TabsResponse.createFrom;
const $$createType10 = $Create.Nullable($$createType5);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $Create.Map($Create.Any, $Create.Any);
const $$createType13 = store$0.CloudVolume.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType13);
const $$createType16 = store$0.RemoteFile.createFrom;
const $$createType17 = $Create.Array($$createType16);
