// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../pkg/store/models.js";

/**
 * MigrationStatus holds information about a directory migration
 */
export class MigrationStatus {
    "count": number;
    "size": number;

    /** Creates a new MigrationStatus instance. */
    constructor($$source: Partial<MigrationStatus> = {}) {
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrationStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrationStatus($$parsedSource as Partial<MigrationStatus>);
    }
}

export class PluginInfo {
    "id": string;
    "name": string;
    "version": string;
    "settingsSchema": { [_ in string]?: string };
    "config": { [_ in string]?: string };
    "enabled": boolean;

    /** Creates a new PluginInfo instance. */
    constructor($$source: Partial<PluginInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("settingsSchema" in $$source)) {
            this["settingsSchema"] = {};
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginInfo {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settingsSchema" in $$parsedSource) {
            $$parsedSource["settingsSchema"] = $$createField3_0($$parsedSource["settingsSchema"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField4_0($$parsedSource["config"]);
        }
        return new PluginInfo($$parsedSource as Partial<PluginInfo>);
    }
}

/**
 * TabsResponse represents a paginated response for tabs
 */
export class TabsResponse {
    "tabs": store$0.Tab[];
    "total": number;
    "page": number;
    "pageSize": number;
    "hasMore": boolean;

    /** Creates a new TabsResponse instance. */
    constructor($$source: Partial<TabsResponse> = {}) {
        if (!("tabs" in $$source)) {
            this["tabs"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TabsResponse {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField0_0($$parsedSource["tabs"]);
        }
        return new TabsResponse($$parsedSource as Partial<TabsResponse>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = store$0.Tab.createFrom;
const $$createType2 = $Create.Array($$createType1);
