// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['app']['App']['AddCategory'](arg1);
}

export function AddTabToCategory(arg1, arg2) {
  return window['go']['app']['App']['AddTabToCategory'](arg1, arg2);
}

export function BatchAddTabsToCategory(arg1, arg2) {
  return window['go']['app']['App']['BatchAddTabsToCategory'](arg1, arg2);
}

export function BatchDeleteTabs(arg1) {
  return window['go']['app']['App']['BatchDeleteTabs'](arg1);
}

export function BatchMoveTabs(arg1, arg2) {
  return window['go']['app']['App']['BatchMoveTabs'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['app']['App']['DeleteCategory'](arg1);
}

export function DeleteTab(arg1) {
  return window['go']['app']['App']['DeleteTab'](arg1);
}

export function DownloadCloudTabToLocal(arg1) {
  return window['go']['app']['App']['DownloadCloudTabToLocal'](arg1);
}

export function ExportTab(arg1, arg2) {
  return window['go']['app']['App']['ExportTab'](arg1, arg2);
}

export function GetCategories() {
  return window['go']['app']['App']['GetCategories']();
}

export function GetCover(arg1) {
  return window['go']['app']['App']['GetCover'](arg1);
}

export function GetFileServerPort() {
  return window['go']['app']['App']['GetFileServerPort']();
}

export function GetRecentCategories(arg1) {
  return window['go']['app']['App']['GetRecentCategories'](arg1);
}

export function GetRecentTabs(arg1) {
  return window['go']['app']['App']['GetRecentTabs'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetTabs() {
  return window['go']['app']['App']['GetTabs']();
}

export function GetTabsPaginated(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['GetTabsPaginated'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function MarkAsOpened(arg1) {
  return window['go']['app']['App']['MarkAsOpened'](arg1);
}

export function MoveCategory(arg1, arg2) {
  return window['go']['app']['App']['MoveCategory'](arg1, arg2);
}

export function MoveTab(arg1, arg2) {
  return window['go']['app']['App']['MoveTab'](arg1, arg2);
}

export function OpenTab(arg1) {
  return window['go']['app']['App']['OpenTab'](arg1);
}

export function ProcessFile(arg1) {
  return window['go']['app']['App']['ProcessFile'](arg1);
}

export function RecalculateAllInitials() {
  return window['go']['app']['App']['RecalculateAllInitials']();
}

export function RemoveTabFromCategory(arg1, arg2) {
  return window['go']['app']['App']['RemoveTabFromCategory'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveTab(arg1, arg2) {
  return window['go']['app']['App']['SaveTab'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['app']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function SelectImage() {
  return window['go']['app']['App']['SelectImage']();
}

export function SetFileServerPort(arg1) {
  return window['go']['app']['App']['SetFileServerPort'](arg1);
}

export function StartFileServer() {
  return window['go']['app']['App']['StartFileServer']();
}

export function TriggerSync() {
  return window['go']['app']['App']['TriggerSync']();
}

export function UpdateTab(arg1) {
  return window['go']['app']['App']['UpdateTab'](arg1);
}

export function UpdateTabCategories(arg1, arg2) {
  return window['go']['app']['App']['UpdateTabCategories'](arg1, arg2);
}

export function UpdateTabMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateTabMetadata'](arg1, arg2, arg3, arg4);
}

export function WebDAVAddOnlineFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WebDAVAddOnlineFiles'](arg1, arg2, arg3, arg4);
}

export function WebDAVCheckStatus() {
  return window['go']['app']['App']['WebDAVCheckStatus']();
}

export function WebDAVDownloadFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WebDAVDownloadFiles'](arg1, arg2, arg3, arg4);
}

export function WebDAVListDir(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WebDAVListDir'](arg1, arg2, arg3, arg4);
}

export function WebDAVListRemoteDirectories(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WebDAVListRemoteDirectories'](arg1, arg2, arg3, arg4);
}

export function WebDAVScanRemoteFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['WebDAVScanRemoteFiles'](arg1, arg2, arg3, arg4);
}

export function WebDAVTestConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['WebDAVTestConnection'](arg1, arg2, arg3);
}

export function WebDAVUploadFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['WebDAVUploadFiles'](arg1, arg2, arg3, arg4, arg5);
}
