// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function GetCover(arg1:string):Promise<string>;

export function GetTabs():Promise<Array<store.Tab>>;

export function OpenTab(arg1:string):Promise<void>;

export function ProcessFile(arg1:string):Promise<store.Tab>;

export function SaveTab(arg1:store.Tab,arg2:boolean):Promise<void>;
