// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCover(arg1) {
  return window['go']['main']['App']['GetCover'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function OpenTab(arg1) {
  return window['go']['main']['App']['OpenTab'](arg1);
}

export function ProcessFile(arg1) {
  return window['go']['main']['App']['ProcessFile'](arg1);
}

export function SaveTab(arg1, arg2) {
  return window['go']['main']['App']['SaveTab'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
