// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function AddCategory(arg1:store.Category):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteTab(arg1:string):Promise<void>;

export function ExportTab(arg1:string,arg2:string):Promise<void>;

export function GetCategories():Promise<Array<store.Category>>;

export function GetCover(arg1:string):Promise<string>;

export function GetSettings():Promise<store.Settings>;

export function GetTabContent(arg1:string):Promise<string>;

export function GetTabs():Promise<Array<store.Tab>>;

export function MoveCategory(arg1:string,arg2:string):Promise<void>;

export function MoveTab(arg1:string,arg2:string):Promise<void>;

export function OpenTab(arg1:string):Promise<void>;

export function ProcessFile(arg1:string):Promise<store.Tab>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function SaveTab(arg1:store.Tab,arg2:boolean):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectImage():Promise<string>;

export function TriggerSync():Promise<string>;

export function UpdateTab(arg1:store.Tab):Promise<void>;
